### ISSUE TITLE
Bolt Build Tools: Static Site Build Broken

### ISSUE THREAD

**Issue by sghoweri** [boltdesignsystem/bolt#1081]
If you try to use Bolt to build / watch / serve a static site (using the `static` env config) the static site keeps regenerating non-stop due to  the watch task looking for `.html` file changes in the build / www folder.

**Comment by LegendT** [comment]
The error I get when trying to build a static site is: 
UnhandledPromiseRejectionWarning: TypeError: handler is not a function  at Watching.compiler.watch [as handler]
Is this the same bug?

**Comment by adamszalapski** [comment]
@LegendT you having this error when running `bolt watch` or `bolt start` in our examples integrations folder or when you run root build?
