### ISSUE TITLE
Prevent non-deterministic package resolution in yarn

### ISSUE THREAD

**Issue by christophersmith262** [boltdesignsystem/bolt#1117]
## Description

If you `yarn add @bolt/components-critical-fonts@2.2.0 @bolt/components-headline@2.2.0` you will get two different versions of the headline component installed.  The directory structure looks like:

<img width="536" alt="Screen Shot 2019-03-17 at 2 50 04 PM" src="https://user-images.githubusercontent.com/4907315/54496336-7bd72d00-48c4-11e9-89be-c72ce4004d93.png">

Since you are using the `npm-sass` package to compile your sass in the bolt build tool, this can lead to unpredictable results depending on how you organize your includes.

This is somewhat of a trivial example since the components-critical-fonts package doesn't actually include the headline scss, but it's the same issue for any component that depends on another component.

```
@import 'components-headline'; // components-headline sass v2.2.0 is included
```

```
@import 'components-critical-font'; // if this had a scss reference to the headline, v2.3.0 is included
@import 'components-headline'; // v2.2.0 is also included. v2.2.0 wins conflicting definitions
```

```
// Same, except v2.3.0 wins the conflicting definition race.
@import 'components-critical-font';
@import 'components-headline';
```

```
@import 'components-critical-font'; // You get headline v2.3.0 scss
```

This has other implications, like ballooning our build sizes since we are installing most packages twice.

This is a result of creating dependencies with `yarn add <dependency> --scope=<topackage>`

## Mitigation

The issues with scss are mostly mitigated by the fact that we explicitly list our sass imports in a specific order, but that is a pretty fragile system.

Using the yarn `resolutions` key can also be used to lock in a single version of a package.

## Resolution

I'd like to see bolt switch from using `^<package-version>` to `<package-version>` for inter-package dependencies since that more accurately reflects how the the system is supposed to be used.

We'd have to go back and fix the packages with `yarn add <dependency> --scope=<topackage> --exact`.

**Comment by sghoweri** [comment]
@christophersmith262 I've got some concerns (for and against this) regarding hot fixes in one package requiring re-releasing a whole bunch of components vs allowing hotfix updates to get auto-pulled in (not auto-updating to minor and major versions obv.). 

Can we chat a bit more about this one?
