### ISSUE TITLE
Consider using sassdoc to generate sass mixin, function, global variable documentation

### ISSUE THREAD

**Issue by christophersmith262** [boltdesignsystem/bolt#1118]
## Description

Instead of playing "ask a bolty" when developers have questions about available sass constructs, can we use something like http://sassdoc.com/getting-started/ to generate documentation?

I've tried running it against a simple bolt entrypoint and it seems to work pretty well.

**Comment by sghoweri** [comment]
@christophersmith262 there's still some work to be done with making this super easy to find + updating the right-hand navigation however we've actually had Sassdoc wired up for a good while now 😉 

https://boltdesignsystem.com/docs/guides/development/sassdocs.html

JSDoc on the other hand is still in the works!

**Comment by sghoweri** [comment]
Closing this out out @christophersmith262 - see comment below (and feel free to reopen if there's something else specifically you were looking for!)

**Comment by charginghawk** [comment]
@sghoweri That link is returning "Cannot GET /docs/guides/development/sassdocs.html".

**Comment by christophersmith262** [comment]
Looks like it moved here:
https://boltdesignsystem.com/docs/development/sassdocs.html

Possible to set up a redirect @sghoweri ?
