### ISSUE TITLE
boltdesignsystem.com components page looks weird after hitting `back`

### ISSUE THREAD

**Issue by shaal** [boltdesignsystem/bolt#1236]
I tested it on Ubuntu 18.04, Chromium, Chrome, Firefox

Steps to replicate:
1. Go to https://boltdesignsystem.com/pattern-lab/?p=components-overview
2. Click on any component (ie. Accordion)
3. Click the `back` button of the browser
Now you are going to see a very long page, scroll down a lot and you'll find somewhere in the middle the list of components

**Comment by margoromo** [comment]
Thank you @shaal! We will take a look at this.

**Comment by margoromo** [comment]
@shaal - we have create BDS-1520 in our internal JIRA to cover this issue. Thank you so much for the heads up!

**Comment by sghoweri** [comment]
@shaal FYI, #1255 (which just got merged down to master) has a few updates which should fix this UIKit bug!
