### ISSUE TITLE
Use of ` background-color: bolt-theme(primary)` delivers same color in IE 11 

### ISSUE THREAD

**Issue by glassdimly** [boltdesignsystem/bolt#1437]
This is in issue with `bolt-theme` (and therefore `bolt-themify`). In [Micro Journeys](http://localhost:3000/pattern-lab/patterns/06-experiments-micro-journeys-90-micro-journeys/06-experiments-micro-journeys-90-micro-journeys.html) on `develop`@`HEAD`. The dot and line Nav (in `nav-shared.scss`) uses `bolt-theme()` but on IE 11 Win 10 the colors don't switch when the theme is switched.

Here's a [video](https://www.dropbox.com/s/ym4fb8n347pm36j/img_8586.mov?dl=0).

Here's a [link to the functionality](https://boltdesignsystem-quyggus2o.now.sh/pattern-lab/patterns/06-experiments-micro-journeys-90-micro-journeys/06-experiments-micro-journeys-90-micro-journeys.html).

Here's a [link to the code controlling the active nav dot](https://github.com/bolt-design-system/bolt/blob/fix/ie-edge-final-fix/packages/micro-journeys/src/nav-shared.scss#L15).

Note: we've also found that passing a `map` to `bolt-theme` with theme-keyed values doesn't work. We'll create a ticket for that today.

**Comment by glassdimly** [comment]
Steps taken:
1. Put sass mixins from `nav-shared.scss` directly into files using them, on the theory that the way webpack was processing imports was missing this file.

Didn't resolve the problem.

**Comment by sghoweri** [comment]
@glassdimly I'm also looking into this one. Will post back once I have some updates on this.

**Comment by sghoweri** [comment]
@glassdimly looking into this, I noticed that you were missing the `content: '';` for the if statement in the Sass you're linking to [here](https://github.com/bolt-design-system/bolt/blob/fix/ie-edge-final-fix/packages/micro-journeys/src/nav-shared.scss#L15)./

Perhaps this is related to the issue here?

**Comment by glassdimly** [comment]
Every `after` gets first processed with the `non-active` state [here](https://github.com/bolt-design-system/bolt/blob/fix/ie-edge-final-fix/packages/micro-journeys/src/nav-shared.scss#L18) so this is not a problem.
